#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class ActividadIndependiente
	{
		private int idActividadIndependiente;
		public virtual int IdActividadIndependiente
		{
			get
			{
				return this.idActividadIndependiente;
			}
			set
			{
				this.idActividadIndependiente = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string sustentoDeVida;
		public virtual string SustentoDeVida
		{
			get
			{
				return this.sustentoDeVida;
			}
			set
			{
				this.sustentoDeVida = value;
			}
		}
		
		private string sustentoDeVidaOtro;
		public virtual string SustentoDeVidaOtro
		{
			get
			{
				return this.sustentoDeVidaOtro;
			}
			set
			{
				this.sustentoDeVidaOtro = value;
			}
		}
		
		private string tiempoActividadFuncionamiento;
		public virtual string TiempoActividadFuncionamiento
		{
			get
			{
				return this.tiempoActividadFuncionamiento;
			}
			set
			{
				this.tiempoActividadFuncionamiento = value;
			}
		}
		
		private string situacionTributaria;
		public virtual string SituacionTributaria
		{
			get
			{
				return this.situacionTributaria;
			}
			set
			{
				this.situacionTributaria = value;
			}
		}
		
		private string estaRegistrado;
		public virtual string EstaRegistrado
		{
			get
			{
				return this.estaRegistrado;
			}
			set
			{
				this.estaRegistrado = value;
			}
		}
		
		private string estaRegistradoOtro;
		public virtual string EstaRegistradoOtro
		{
			get
			{
				return this.estaRegistradoOtro;
			}
			set
			{
				this.estaRegistradoOtro = value;
			}
		}
		
		private string tieneEmpleadosACargo;
		public virtual string TieneEmpleadosACargo
		{
			get
			{
				return this.tieneEmpleadosACargo;
			}
			set
			{
				this.tieneEmpleadosACargo = value;
			}
		}
		
		private string cantidadEmpleadosACargo;
		public virtual string CantidadEmpleadosACargo
		{
			get
			{
				return this.cantidadEmpleadosACargo;
			}
			set
			{
				this.cantidadEmpleadosACargo = value;
			}
		}
		
		private bool? feriasItinerantes;
		public virtual bool? FeriasItinerantes
		{
			get
			{
				return this.feriasItinerantes;
			}
			set
			{
				this.feriasItinerantes = value;
			}
		}
		
		private bool? internetWeb;
		public virtual bool? InternetWeb
		{
			get
			{
				return this.internetWeb;
			}
			set
			{
				this.internetWeb = value;
			}
		}
		
		private bool? internetRedesSociales;
		public virtual bool? InternetRedesSociales
		{
			get
			{
				return this.internetRedesSociales;
			}
			set
			{
				this.internetRedesSociales = value;
			}
		}
		
		private bool? localEstudioPropio;
		public virtual bool? LocalEstudioPropio
		{
			get
			{
				return this.localEstudioPropio;
			}
			set
			{
				this.localEstudioPropio = value;
			}
		}
		
		private bool? localesOficinas;
		public virtual bool? LocalesOficinas
		{
			get
			{
				return this.localesOficinas;
			}
			set
			{
				this.localesOficinas = value;
			}
		}
		
		private bool? oficinaPrivadaShowroom;
		public virtual bool? OficinaPrivadaShowroom
		{
			get
			{
				return this.oficinaPrivadaShowroom;
			}
			set
			{
				this.oficinaPrivadaShowroom = value;
			}
		}
		
		private string comoComercializaOtro;
		public virtual string ComoComercializaOtro
		{
			get
			{
				return this.comoComercializaOtro;
			}
			set
			{
				this.comoComercializaOtro = value;
			}
		}
		
		private string nombreEspacio;
		public virtual string NombreEspacio
		{
			get
			{
				return this.nombreEspacio;
			}
			set
			{
				this.nombreEspacio = value;
			}
		}
		
		private string linkEspacio;
		public virtual string LinkEspacio
		{
			get
			{
				return this.linkEspacio;
			}
			set
			{
				this.linkEspacio = value;
			}
		}
		
		private string ubicacionEspacio;
		public virtual string UbicacionEspacio
		{
			get
			{
				return this.ubicacionEspacio;
			}
			set
			{
				this.ubicacionEspacio = value;
			}
		}
		
		private bool? fondosPropios;
		public virtual bool? FondosPropios
		{
			get
			{
				return this.fondosPropios;
			}
			set
			{
				this.fondosPropios = value;
			}
		}
		
		private bool? prestamosEntidadesPrivadas;
		public virtual bool? PrestamosEntidadesPrivadas
		{
			get
			{
				return this.prestamosEntidadesPrivadas;
			}
			set
			{
				this.prestamosEntidadesPrivadas = value;
			}
		}
		
		private bool? prestamosEntidadesPublicas;
		public virtual bool? PrestamosEntidadesPublicas
		{
			get
			{
				return this.prestamosEntidadesPublicas;
			}
			set
			{
				this.prestamosEntidadesPublicas = value;
			}
		}
		
		private bool? sociosCapitalistas;
		public virtual bool? SociosCapitalistas
		{
			get
			{
				return this.sociosCapitalistas;
			}
			set
			{
				this.sociosCapitalistas = value;
			}
		}
		
		private bool? gananciasGenerales;
		public virtual bool? GananciasGenerales
		{
			get
			{
				return this.gananciasGenerales;
			}
			set
			{
				this.gananciasGenerales = value;
			}
		}
		
		private string comoFinanciaActividadProfesionalOtro;
		public virtual string ComoFinanciaActividadProfesionalOtro
		{
			get
			{
				return this.comoFinanciaActividadProfesionalOtro;
			}
			set
			{
				this.comoFinanciaActividadProfesionalOtro = value;
			}
		}
		
		private string realizaVentasServicios;
		public virtual string RealizaVentasServicios
		{
			get
			{
				return this.realizaVentasServicios;
			}
			set
			{
				this.realizaVentasServicios = value;
			}
		}
		
		private string cuales;
		public virtual string Cuales
		{
			get
			{
				return this.cuales;
			}
			set
			{
				this.cuales = value;
			}
		}
		
		private bool? sinFinanciamiento;
		public virtual bool? SinFinanciamiento
		{
			get
			{
				return this.sinFinanciamiento;
			}
			set
			{
				this.sinFinanciamiento = value;
			}
		}
		
		private bool? noComercializaAun;
		public virtual bool? NoComercializaAun
		{
			get
			{
				return this.noComercializaAun;
			}
			set
			{
				this.noComercializaAun = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
