#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class ActividadProfesional
	{
		private int idActividadProfesional;
		public virtual int IdActividadProfesional
		{
			get
			{
				return this.idActividadProfesional;
			}
			set
			{
				this.idActividadProfesional = value;
			}
		}
		
		private string disciplinaProyectual;
		public virtual string DisciplinaProyectual
		{
			get
			{
				return this.disciplinaProyectual;
			}
			set
			{
				this.disciplinaProyectual = value;
			}
		}
		
		private string disciplinaProyectualOtra;
		public virtual string DisciplinaProyectualOtra
		{
			get
			{
				return this.disciplinaProyectualOtra;
			}
			set
			{
				this.disciplinaProyectualOtra = value;
			}
		}
		
		private string subSector;
		public virtual string SubSector
		{
			get
			{
				return this.subSector;
			}
			set
			{
				this.subSector = value;
			}
		}
		
		private string tipoRelacionLaboral;
		public virtual string TipoRelacionLaboral
		{
			get
			{
				return this.tipoRelacionLaboral;
			}
			set
			{
				this.tipoRelacionLaboral = value;
			}
		}
		
		private string tipoRelacionLaboralOtro;
		public virtual string TipoRelacionLaboralOtro
		{
			get
			{
				return this.tipoRelacionLaboralOtro;
			}
			set
			{
				this.tipoRelacionLaboralOtro = value;
			}
		}
		
		private string nombreEmpresa;
		public virtual string NombreEmpresa
		{
			get
			{
				return this.nombreEmpresa;
			}
			set
			{
				this.nombreEmpresa = value;
			}
		}
		
		private string linkEmpresa;
		public virtual string LinkEmpresa
		{
			get
			{
				return this.linkEmpresa;
			}
			set
			{
				this.linkEmpresa = value;
			}
		}
		
		private string descripcion;
		public virtual string Descripcion
		{
			get
			{
				return this.descripcion;
			}
			set
			{
				this.descripcion = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
