#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class ActividadProfesional
	{
		private int idActividadProfesional;
		public virtual int IdActividadProfesional
		{
			get
			{
				return this.idActividadProfesional;
			}
			set
			{
				this.idActividadProfesional = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string disciplinaProyectual;
		public virtual string DisciplinaProyectual
		{
			get
			{
				return this.disciplinaProyectual;
			}
			set
			{
				this.disciplinaProyectual = value;
			}
		}
		
		private string disciplinaProyectualOtra;
		public virtual string DisciplinaProyectualOtra
		{
			get
			{
				return this.disciplinaProyectualOtra;
			}
			set
			{
				this.disciplinaProyectualOtra = value;
			}
		}
		
		private bool? accesorios;
		public virtual bool? Accesorios
		{
			get
			{
				return this.accesorios;
			}
			set
			{
				this.accesorios = value;
			}
		}
		
		private bool? calzado;
		public virtual bool? Calzado
		{
			get
			{
				return this.calzado;
			}
			set
			{
				this.calzado = value;
			}
		}
		
		private bool? ceramica;
		public virtual bool? Ceramica
		{
			get
			{
				return this.ceramica;
			}
			set
			{
				this.ceramica = value;
			}
		}
		
		private bool? disenioEditorial;
		public virtual bool? DisenioEditorial
		{
			get
			{
				return this.disenioEditorial;
			}
			set
			{
				this.disenioEditorial = value;
			}
		}
		
		private bool? disenioWeb;
		public virtual bool? DisenioWeb
		{
			get
			{
				return this.disenioWeb;
			}
			set
			{
				this.disenioWeb = value;
			}
		}
		
		private bool? joyeria;
		public virtual bool? Joyeria
		{
			get
			{
				return this.joyeria;
			}
			set
			{
				this.joyeria = value;
			}
		}
		
		private bool? madera;
		public virtual bool? Madera
		{
			get
			{
				return this.madera;
			}
			set
			{
				this.madera = value;
			}
		}
		
		private bool? mobiliario;
		public virtual bool? Mobiliario
		{
			get
			{
				return this.mobiliario;
			}
			set
			{
				this.mobiliario = value;
			}
		}
		
		private bool? tejidos;
		public virtual bool? Tejidos
		{
			get
			{
				return this.tejidos;
			}
			set
			{
				this.tejidos = value;
			}
		}
		
		private string subSectorOtro;
		public virtual string SubSectorOtro
		{
			get
			{
				return this.subSectorOtro;
			}
			set
			{
				this.subSectorOtro = value;
			}
		}
		
		private string tipoRelacionLaboral;
		public virtual string TipoRelacionLaboral
		{
			get
			{
				return this.tipoRelacionLaboral;
			}
			set
			{
				this.tipoRelacionLaboral = value;
			}
		}
		
		private string tipoRelacionLaboralOtro;
		public virtual string TipoRelacionLaboralOtro
		{
			get
			{
				return this.tipoRelacionLaboralOtro;
			}
			set
			{
				this.tipoRelacionLaboralOtro = value;
			}
		}
		
		private string nombreEmpresaAP;
		public virtual string NombreEmpresaAP
		{
			get
			{
				return this.nombreEmpresaAP;
			}
			set
			{
				this.nombreEmpresaAP = value;
			}
		}
		
		private string linkEmpresaAP;
		public virtual string LinkEmpresaAP
		{
			get
			{
				return this.linkEmpresaAP;
			}
			set
			{
				this.linkEmpresaAP = value;
			}
		}
		
		private string descripcionAP;
		public virtual string DescripcionAP
		{
			get
			{
				return this.descripcionAP;
			}
			set
			{
				this.descripcionAP = value;
			}
		}
		
		private bool? plasticas;
		public virtual bool? Plasticas
		{
			get
			{
				return this.plasticas;
			}
			set
			{
				this.plasticas = value;
			}
		}
		
		private bool? musicales;
		public virtual bool? Musicales
		{
			get
			{
				return this.musicales;
			}
			set
			{
				this.musicales = value;
			}
		}
		
		private bool? literarias;
		public virtual bool? Literarias
		{
			get
			{
				return this.literarias;
			}
			set
			{
				this.literarias = value;
			}
		}
		
		private bool? graficas;
		public virtual bool? Graficas
		{
			get
			{
				return this.graficas;
			}
			set
			{
				this.graficas = value;
			}
		}
		
		private bool? escenicas;
		public virtual bool? Escenicas
		{
			get
			{
				return this.escenicas;
			}
			set
			{
				this.escenicas = value;
			}
		}
		
		private bool? digitales;
		public virtual bool? Digitales
		{
			get
			{
				return this.digitales;
			}
			set
			{
				this.digitales = value;
			}
		}
		
		private bool? cinematograficas;
		public virtual bool? Cinematograficas
		{
			get
			{
				return this.cinematograficas;
			}
			set
			{
				this.cinematograficas = value;
			}
		}
		
		private bool? audiovisuales;
		public virtual bool? Audiovisuales
		{
			get
			{
				return this.audiovisuales;
			}
			set
			{
				this.audiovisuales = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
