#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CapaDominio	
{
	public partial class Employee
	{
		private int idEmployee;
		public virtual int IdEmployee
		{
			get
			{
				return this.idEmployee;
			}
			set
			{
				this.idEmployee = value;
			}
		}
		
		private string lastname;
		public virtual string Lastname
		{
			get
			{
				return this.lastname;
			}
			set
			{
				this.lastname = value;
			}
		}
		
		private string title;
		public virtual string Title
		{
			get
			{
				return this.title;
			}
			set
			{
				this.title = value;
			}
		}
		
	}
}
#pragma warning restore 1591
