#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class FormacionAcademica
	{
		private int idFormacionAcademica;
		public virtual int IdFormacionAcademica
		{
			get
			{
				return this.idFormacionAcademica;
			}
			set
			{
				this.idFormacionAcademica = value;
			}
		}
		
		private string estudiosOficiales;
		public virtual string EstudiosOficiales
		{
			get
			{
				return this.estudiosOficiales;
			}
			set
			{
				this.estudiosOficiales = value;
			}
		}
		
		private string estudiosOficialesOtro;
		public virtual string EstudiosOficialesOtro
		{
			get
			{
				return this.estudiosOficialesOtro;
			}
			set
			{
				this.estudiosOficialesOtro = value;
			}
		}
		
		private string tituloObtenido;
		public virtual string TituloObtenido
		{
			get
			{
				return this.tituloObtenido;
			}
			set
			{
				this.tituloObtenido = value;
			}
		}
		
		private string institucionEmisoraTitulo;
		public virtual string InstitucionEmisoraTitulo
		{
			get
			{
				return this.institucionEmisoraTitulo;
			}
			set
			{
				this.institucionEmisoraTitulo = value;
			}
		}
		
		private string otrosEstudios;
		public virtual string OtrosEstudios
		{
			get
			{
				return this.otrosEstudios;
			}
			set
			{
				this.otrosEstudios = value;
			}
		}
		
		private bool? esEstudiante;
		public virtual bool? EsEstudiante
		{
			get
			{
				return this.esEstudiante;
			}
			set
			{
				this.esEstudiante = value;
			}
		}
		
		private string carreraNombre;
		public virtual string CarreraNombre
		{
			get
			{
				return this.carreraNombre;
			}
			set
			{
				this.carreraNombre = value;
			}
		}
		
		private string carreraAnioIngreso;
		public virtual string CarreraAnioIngreso
		{
			get
			{
				return this.carreraAnioIngreso;
			}
			set
			{
				this.carreraAnioIngreso = value;
			}
		}
		
		private string carreraAnioCursada;
		public virtual string CarreraAnioCursada
		{
			get
			{
				return this.carreraAnioCursada;
			}
			set
			{
				this.carreraAnioCursada = value;
			}
		}
		
		private string carreraDuracion;
		public virtual string CarreraDuracion
		{
			get
			{
				return this.carreraDuracion;
			}
			set
			{
				this.carreraDuracion = value;
			}
		}
		
		private string carreraInstitucion;
		public virtual string CarreraInstitucion
		{
			get
			{
				return this.carreraInstitucion;
			}
			set
			{
				this.carreraInstitucion = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
