#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Innovacion
	{
		private int idInnovacion;
		public virtual int IdInnovacion
		{
			get
			{
				return this.idInnovacion;
			}
			set
			{
				this.idInnovacion = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string incorporaInnovacion;
		public virtual string IncorporaInnovacion
		{
			get
			{
				return this.incorporaInnovacion;
			}
			set
			{
				this.incorporaInnovacion = value;
			}
		}
		
		private string incorporaInnovacionOtra;
		public virtual string IncorporaInnovacionOtra
		{
			get
			{
				return this.incorporaInnovacionOtra;
			}
			set
			{
				this.incorporaInnovacionOtra = value;
			}
		}
		
		private bool? legales;
		public virtual bool? Legales
		{
			get
			{
				return this.legales;
			}
			set
			{
				this.legales = value;
			}
		}
		
		private bool? financieras;
		public virtual bool? Financieras
		{
			get
			{
				return this.financieras;
			}
			set
			{
				this.financieras = value;
			}
		}
		
		private bool? problemasTecnicos;
		public virtual bool? ProblemasTecnicos
		{
			get
			{
				return this.problemasTecnicos;
			}
			set
			{
				this.problemasTecnicos = value;
			}
		}
		
		private bool? recursosHumanos;
		public virtual bool? RecursosHumanos
		{
			get
			{
				return this.recursosHumanos;
			}
			set
			{
				this.recursosHumanos = value;
			}
		}
		
		private string dificultadesOtra;
		public virtual string DificultadesOtra
		{
			get
			{
				return this.dificultadesOtra;
			}
			set
			{
				this.dificultadesOtra = value;
			}
		}
		
		private string comoTomaronInnovacion;
		public virtual string ComoTomaronInnovacion
		{
			get
			{
				return this.comoTomaronInnovacion;
			}
			set
			{
				this.comoTomaronInnovacion = value;
			}
		}
		
		private string contarExperiencia;
		public virtual string ContarExperiencia
		{
			get
			{
				return this.contarExperiencia;
			}
			set
			{
				this.contarExperiencia = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
