#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Maquinarium
	{
		private int idMaquinaria;
		public virtual int IdMaquinaria
		{
			get
			{
				return this.idMaquinaria;
			}
			set
			{
				this.idMaquinaria = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string disponeEquipo;
		public virtual string DisponeEquipo
		{
			get
			{
				return this.disponeEquipo;
			}
			set
			{
				this.disponeEquipo = value;
			}
		}
		
		private bool? equiposPropios;
		public virtual bool? EquiposPropios
		{
			get
			{
				return this.equiposPropios;
			}
			set
			{
				this.equiposPropios = value;
			}
		}
		
		private bool? equiposPrestados;
		public virtual bool? EquiposPrestados
		{
			get
			{
				return this.equiposPrestados;
			}
			set
			{
				this.equiposPrestados = value;
			}
		}
		
		private bool? equiposAlquilados;
		public virtual bool? EquiposAlquilados
		{
			get
			{
				return this.equiposAlquilados;
			}
			set
			{
				this.equiposAlquilados = value;
			}
		}
		
		private string disponeEquipoOtro;
		public virtual string DisponeEquipoOtro
		{
			get
			{
				return this.disponeEquipoOtro;
			}
			set
			{
				this.disponeEquipoOtro = value;
			}
		}
		
		private bool? maquinas;
		public virtual bool? Maquinas
		{
			get
			{
				return this.maquinas;
			}
			set
			{
				this.maquinas = value;
			}
		}
		
		private bool? recursosInformaticos;
		public virtual bool? RecursosInformaticos
		{
			get
			{
				return this.recursosInformaticos;
			}
			set
			{
				this.recursosInformaticos = value;
			}
		}
		
		private bool? herramientas;
		public virtual bool? Herramientas
		{
			get
			{
				return this.herramientas;
			}
			set
			{
				this.herramientas = value;
			}
		}
		
		private bool? espacio;
		public virtual bool? Espacio
		{
			get
			{
				return this.espacio;
			}
			set
			{
				this.espacio = value;
			}
		}
		
		private bool? manoDeObra;
		public virtual bool? ManoDeObra
		{
			get
			{
				return this.manoDeObra;
			}
			set
			{
				this.manoDeObra = value;
			}
		}
		
		private string falenciaOtra;
		public virtual string FalenciaOtra
		{
			get
			{
				return this.falenciaOtra;
			}
			set
			{
				this.falenciaOtra = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
