#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Producto
	{
		private int idProducto;
		public virtual int IdProducto
		{
			get
			{
				return this.idProducto;
			}
			set
			{
				this.idProducto = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string cantidadProductosAnio;
		public virtual string CantidadProductosAnio
		{
			get
			{
				return this.cantidadProductosAnio;
			}
			set
			{
				this.cantidadProductosAnio = value;
			}
		}
		
		private bool? talleresPropios;
		public virtual bool? TalleresPropios
		{
			get
			{
				return this.talleresPropios;
			}
			set
			{
				this.talleresPropios = value;
			}
		}
		
		private bool? talleresTercerizados;
		public virtual bool? TalleresTercerizados
		{
			get
			{
				return this.talleresTercerizados;
			}
			set
			{
				this.talleresTercerizados = value;
			}
		}
		
		private string dondeRealizaProduccionOtro;
		public virtual string DondeRealizaProduccionOtro
		{
			get
			{
				return this.dondeRealizaProduccionOtro;
			}
			set
			{
				this.dondeRealizaProduccionOtro = value;
			}
		}
		
		private string porcentajeProcesoProductivoNeuquen;
		public virtual string PorcentajeProcesoProductivoNeuquen
		{
			get
			{
				return this.porcentajeProcesoProductivoNeuquen;
			}
			set
			{
				this.porcentajeProcesoProductivoNeuquen = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
