#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class RedesSociale
	{
		private int idRedesSociales;
		public virtual int IdRedesSociales
		{
			get
			{
				return this.idRedesSociales;
			}
			set
			{
				this.idRedesSociales = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private string facebook;
		public virtual string Facebook
		{
			get
			{
				return this.facebook;
			}
			set
			{
				this.facebook = value;
			}
		}
		
		private string instagram;
		public virtual string Instagram
		{
			get
			{
				return this.instagram;
			}
			set
			{
				this.instagram = value;
			}
		}
		
		private string twitter;
		public virtual string Twitter
		{
			get
			{
				return this.twitter;
			}
			set
			{
				this.twitter = value;
			}
		}
		
		private string youtube;
		public virtual string Youtube
		{
			get
			{
				return this.youtube;
			}
			set
			{
				this.youtube = value;
			}
		}
		
		private string flicker;
		public virtual string Flicker
		{
			get
			{
				return this.flicker;
			}
			set
			{
				this.flicker = value;
			}
		}
		
		private bool? redesSociales;
		public virtual bool? RedesSociales
		{
			get
			{
				return this.redesSociales;
			}
			set
			{
				this.redesSociales = value;
			}
		}
		
		private bool? mercadoLibre;
		public virtual bool? MercadoLibre
		{
			get
			{
				return this.mercadoLibre;
			}
			set
			{
				this.mercadoLibre = value;
			}
		}
		
		private bool? sitioWeb;
		public virtual bool? SitioWeb
		{
			get
			{
				return this.sitioWeb;
			}
			set
			{
				this.sitioWeb = value;
			}
		}
		
		private bool? tiendaNube;
		public virtual bool? TiendaNube
		{
			get
			{
				return this.tiendaNube;
			}
			set
			{
				this.tiendaNube = value;
			}
		}
		
		private bool? ferias;
		public virtual bool? Ferias
		{
			get
			{
				return this.ferias;
			}
			set
			{
				this.ferias = value;
			}
		}
		
		private bool? localComercial;
		public virtual bool? LocalComercial
		{
			get
			{
				return this.localComercial;
			}
			set
			{
				this.localComercial = value;
			}
		}
		
		private bool? personal;
		public virtual bool? Personal
		{
			get
			{
				return this.personal;
			}
			set
			{
				this.personal = value;
			}
		}
		
		private bool? showRoom;
		public virtual bool? ShowRoom
		{
			get
			{
				return this.showRoom;
			}
			set
			{
				this.showRoom = value;
			}
		}
		
		private bool? noComercializa;
		public virtual bool? NoComercializa
		{
			get
			{
				return this.noComercializa;
			}
			set
			{
				this.noComercializa = value;
			}
		}
		
		private string plataformaOtra;
		public virtual string PlataformaOtra
		{
			get
			{
				return this.plataformaOtra;
			}
			set
			{
				this.plataformaOtra = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
