#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class Vinculacion
	{
		private int idVinculacion;
		public virtual int IdVinculacion
		{
			get
			{
				return this.idVinculacion;
			}
			set
			{
				this.idVinculacion = value;
			}
		}
		
		private bool? recibioApoyo;
		public virtual bool? RecibioApoyo
		{
			get
			{
				return this.recibioApoyo;
			}
			set
			{
				this.recibioApoyo = value;
			}
		}
		
		private string apoyo;
		public virtual string Apoyo
		{
			get
			{
				return this.apoyo;
			}
			set
			{
				this.apoyo = value;
			}
		}
		
		private string otroApoyo;
		public virtual string OtroApoyo
		{
			get
			{
				return this.otroApoyo;
			}
			set
			{
				this.otroApoyo = value;
			}
		}
		
		private string organismoApoyo;
		public virtual string OrganismoApoyo
		{
			get
			{
				return this.organismoApoyo;
			}
			set
			{
				this.organismoApoyo = value;
			}
		}
		
		private int? organismoApoyoAnio;
		public virtual int? OrganismoApoyoAnio
		{
			get
			{
				return this.organismoApoyoAnio;
			}
			set
			{
				this.organismoApoyoAnio = value;
			}
		}
		
		private string selloBuenDisenioArgentino;
		public virtual string SelloBuenDisenioArgentino
		{
			get
			{
				return this.selloBuenDisenioArgentino;
			}
			set
			{
				this.selloBuenDisenioArgentino = value;
			}
		}
		
		private string mercadoIndustriasCreativasArgentinas;
		public virtual string MercadoIndustriasCreativasArgentinas
		{
			get
			{
				return this.mercadoIndustriasCreativasArgentinas;
			}
			set
			{
				this.mercadoIndustriasCreativasArgentinas = value;
			}
		}
		
		private string aporteCdneu;
		public virtual string AporteCdneu
		{
			get
			{
				return this.aporteCdneu;
			}
			set
			{
				this.aporteCdneu = value;
			}
		}
		
		private string otroAporteCdneu;
		public virtual string OtroAporteCdneu
		{
			get
			{
				return this.otroAporteCdneu;
			}
			set
			{
				this.otroAporteCdneu = value;
			}
		}
		
		private string comentariosFinales;
		public virtual string ComentariosFinales
		{
			get
			{
				return this.comentariosFinales;
			}
			set
			{
				this.comentariosFinales = value;
			}
		}
		
		private int idUsuario;
		public virtual int IdUsuario
		{
			get
			{
				return this.idUsuario;
			}
			set
			{
				this.idUsuario = value;
			}
		}
		
		private Usuario usuario;
		public virtual Usuario Usuario
		{
			get
			{
				return this.usuario;
			}
			set
			{
				this.usuario = value;
			}
		}
		
	}
}
#pragma warning restore 1591
